
import { SentinelCore } from './web/services/SentinelCore';

async function testSentinelCore() {
    console.log("Testing SentinelCore...");

    // Simulate database missing columns for audit
    // Note: auditDatabase attempts to connect to DB. We can test generateMigrationPatch logic directly.

    console.log("--- Patch Generation Logic ---");
    const missing = ['lobbies.scheduled_start', 'lobbies.notes'];
    const patch = SentinelCore.generateMigrationPatch(missing);
    console.log(patch);

    if (patch.includes("ADD COLUMN IF NOT EXISTS scheduled_start TIMESTAMPTZ")) {
        console.log("PASS: scheduled_start detected");
    } else {
        console.log("FAIL: scheduled_start missing");
    }

    if (patch.includes("-- Manual Migration Patch generated by SentinelCore")) {
        console.log("PASS: Header correct");
    }

    console.log("Done.");
}

testSentinelCore();
