import { createClient } from '@/utils/supabase/server';

type Manifest = {
    [table: string]: string[];
};

const SCHEMA_MANIFEST: Manifest = {
    'lobby_players': ['status'],
    'lobbies': ['scheduled_start', 'notes', 'sector_key', 'creator_id'],
    'matches': ['id', 'game_mode_id', 'winner_team', 'approval_status'],
    'match_players': ['match_id', 'user_id', 'team']
};

export const SentinelCore = {
    /**
     * core auditing function that checks for missing columns strictly based on the manifest.
     */
    async auditDatabase(): Promise<{ synced: boolean; missing: string[]; sql_patch: string }> {
        const supabase = await createClient();
        const missing: string[] = [];


        await Promise.all(
            Object.entries(SCHEMA_MANIFEST).map(async ([table, columns]) => {
                for (const column of columns) {
                    try {
                        const { error } = await supabase
                            .from(table)
                            .select(column)
                            .limit(0)
                            .maybeSingle();

                        if (error) {
                            console.warn(`[SentinelCore] Probe failed for ${table}.${column}:`, error.message);
                            missing.push(`${table}.${column}`);
                        }
                    } catch (e) {
                        console.warn(`[SentinelCore] Exception for ${table}.${column}:`, e);
                        missing.push(`${table}.${column}`);
                    }
                }
            })
        );

        const sql_patch = this.generateMigrationPatch(missing);

        return {
            synced: missing.length === 0,
            missing,
            sql_patch
        };
    },

    generateMigrationPatch(missing: string[]): string {
        if (missing.length === 0) return "-- No missing columns detected.";

        const lines = ["-- Manual Migration Patch generated by SentinelCore"];

        missing.forEach(item => {
            const [table, column] = item.split('.');
            if (!table || !column) return;

            let type = "TEXT";
            let def = "NULL";

            if (column === 'status') {
                type = "TEXT";
                def = "'pending'";
            } else if (column === 'scheduled_start') {
                type = "TIMESTAMPTZ";
                def = "NULL";
            } else if (column === 'notes') {
                type = "TEXT";
                def = "''";
            } else if (column === 'sector_key') {
                type = "TEXT";
                def = "NULL";
            } else if (column.endsWith('_id')) {
                type = "BIGINT";
            } else if (column === 'is_active') {
                type = "BOOLEAN";
                def = "true";
            }

            lines.push(`ALTER TABLE public.${table} ADD COLUMN IF NOT EXISTS ${column} ${type} DEFAULT ${def};`);
        });

        return lines.join('\n');
    }
};
